# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-26 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20170126_1827'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cu',
            new_name='Gender',
        ),
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'gender'},
        ),
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
