# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-02-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_auto_20170201_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=1),
        ),
    ]
